name: ESLint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'  # Only trigger on changes in src directory
  pull_request:
    branches: [ "main", "develop"]
    paths:
      - 'src/**'  # Only trigger on changes in src directory

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint on src directory only
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint src/
        continue-on-error: true
