name: Sync Repositories prod (main)

on:
  push:
    branches:
      - main  # Specify the branch that triggers this workflow

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository (Repo B)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: repo-b

      - name: Checkout target repository (Repo A)
        uses: actions/checkout@v4
        with:
          repository: g4ze/tago  # Replace with actual owner/repo-name
          token: ${{ secrets.PAT_TOKEN }}  # Personal Access Token with repo access
          fetch-depth: 0
          path: repo-a
          
      - name: Sync files from Repo B to Repo A
        run: |
          rsync -av --exclude=".git" repo-b/ repo-a/
          cd repo-a
          
          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Check for changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Sync changes from repository B"
            git push origin main
          else
            echo "No changes to commit"
          fi
