name: Sync Repositories prod (main)

on: 
  push:
    branches:
      - main 
  
jobs:
 

  sync-repos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository (Repo B)
        uses: actions/checkout@v4
        with:
          path: repo-b
          
      - name: Checkout target repository (Repo A)
        uses: actions/checkout@v4
        with:
          repository: g4ze/tago  # Replace with actual owner/repo-name
          token: ${{ secrets.PAT_TOKEN }}  # Personal Access Token with repo access
          path: repo-a
          
      - name: Copy files and push
        run: |
          # Remove all contents of Repo A except .git directory
          find repo-a -mindepth 1 -not -name ".git" -exec rm -rf {} +

          # Copy everything from Repo B to Repo A (excluding .git)
          cp -r repo-b/* repo-a/
          cd repo-a
          
          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # Check for changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Hard sync from Repo B (overwriting all files)"
            git push origin main --force
          else
            echo "No changes to commit"
          fi
